version: 2.1

executors:
  android-executor:
    docker:
      - image: circleci/android:api-30
        auth:
          username: chrimaeon
          password: $DOCKERHUB_PASSWORD
    working_directory: ~/app-rater
    environment:
      JAVA_TOOL_OPTIONS: "-Xmx3G"
      GRADLE_OPTS: "-Dorg.gradle.daemon=false -Dorg.gradle.parallel=false -Dorg.gradle.workers.max=2 -Dkotlin.compiler.execution.strategy=in-process -Dkotlin.incremental=false"
      TERM: dumb

commands:
  store-app-rater-artifacts:
    description: "It stores Lint & Test Artifacts"
    parameters:
      artifact-path:
        type: string
    steps:
      - store_artifacts:
          path: <<parameters.artifact-path>>
  store-app-rater-test-results:
    description: "It stores Test Results"
    parameters:
      test-result-path:
        type: string
    steps:
      - store_test_results:
          path: <<parameters.test-result-path>>
  restore-gradle-wrapper:
    description: "Restores Gradle Wrapper from cache"
    steps:
      - restore_cache:
          key: v1-gradle-wrapper-{{ checksum "gradle/wrapper/gradle-wrapper.properties" }}
  save-gradle-wrapper:
    description: "Save Gradle Wrapper to cache"
    steps:
      - save_cache:
          paths:
            - ~/.gradle/wrapper
          key: v1-gradle-wrapper-{{ checksum "gradle/wrapper/gradle-wrapper.properties" }}

jobs:
  build-test:
    executor: android-executor
    steps:
      - checkout
      - restore-gradle-wrapper
      - run:
          name: Download Dependencies
          command: ./gradlew androidDependencies
      - run:
          name: Run JVM Tests & Lint
          command: ./gradlew :library:check :library-ktx:check
      - run:
          name: Gather Lint & Test results
          command: python ./scripts/copy_results
      - store-app-rater-artifacts:
          artifact-path: ci_results/lint
      - store-app-rater-test-results:
          test-result-path: ci_results/test
      - save-gradle-wrapper
      - persist_to_workspace:
          root: .
          paths:
            - build
            - ./**/build
  deploy:
    executor: android-executor
    steps:
      - checkout
      - attach_workspace:
          at: .
      - restore-gradle-wrapper
      - run:
          name: Deploy to Sonatype
          command: ./gradlew publishLibraryMavenPublicationToSonatypeRepository
  createRelease:
    executor: android-executor
    steps:
      - checkout
      - attach_workspace:
          at: .
      - restore-gradle-wrapper
      - run:
          name: Create Github Release notes
          command: ./gradlew createGithubRelease

workflows:
  version: 2
  build-and-test:
    jobs:
      - build-test:
          context:
            - DockerHub
          filters:
            tags:
              only: /.*/
            branches:
              only:
                - develop
                - master
                - /release\/.*/
# reenable once signing works
#      - hold-deploy:
#          type: approval
#          context:
#            - DockerHub
#          requires:
#            - build-test
#          filters:
#            tags:
#              only: /.*/
#            branches:
#              ignore: /.*/
#      - deploy:
#          context:
#            - DockerHub
#          requires:
#            - hold-deploy
#          filters:
#            tags:
#              only: /.*/
#            branches:
#              ignore: /.*/
#      - hold-release:
#          type: approval
#          context:
#            - DockerHub
#          requires:
#            - deploy
#          filters:
#            tags:
#              only: /.*/
#            branches:
#              ignore: /.*/
#      - createRelease:
#          context:
#            - DockerHub
#          requires:
#            - hold-release
#          filters:
#            tags:
#              only: /.*/
#            branches:
#              ignore: /.*/
